version: '3.11'

services:
  server:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src/:/src/
    command: uvicorn app.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000